import type { SVGAttributes } from "react";
import type { IconName } from "./icon-names";
import {
	VscAccount,
	VscAdd,
	VscArrowDown,
	VscArrowLeft,
	VscArrowRight,
	VscArrowUp,
	VscBeaker,
	VscBell,
	VscBook,
	VscBookmark,
	VscBug,
	VscCalendar,
	VscCheck,
	VscClose,
	VscCloud,
	VscCopy,
	VscDatabase,
	VscDiff,
	VscEdit,
	VscError,
	VscExtensions,
	VscEye,
	VscEyeClosed,
	VscFile,
	VscFileBinary,
	VscFileCode,
	VscFileMedia,
	VscFilePdf,
	VscFileSubmodule,
	VscFileSymlinkFile,
	VscFileZip,
	VscFiles,
	VscFlame,
	VscFolder,
	VscFolderActive,
	VscFolderLibrary,
	VscFolderOpened,
	VscGear,
	VscGitCommit,
	VscGitMerge,
	VscGitPullRequest,
	VscGithub,
	VscGlobe,
	VscGraph,
	VscHistory,
	VscHome,
	VscInfo,
	VscJson,
	VscKey,
	VscLayers,
	VscLayout,
	VscLink,
	VscLinkExternal,
	VscListFlat,
	VscListTree,
	VscLock,
	VscMail,
	VscMarkdown,
	VscMic,
	VscMute,
	VscNewFile,
	VscNewFolder,
	VscNote,
	VscNotebook,
	VscPackage,
	VscPerson,
	VscPlay,
	VscPlug,
	VscRecord,
	VscRefresh,
	VscRemote,
	VscReply,
	VscRepo,
	VscRepoForked,
	VscRocket,
	VscRootFolder,
	VscRootFolderOpened,
	VscSave,
	VscSearch,
	VscSend,
	VscServer,
	VscSettings,
	VscSettingsGear,
	VscShield,
	VscStarEmpty,
	VscStarFull,
	VscSymbolClass,
	VscSymbolEnum,
	VscSymbolInterface,
	VscSymbolMethod,
	VscSymbolMisc,
	VscSymbolNamespace,
	VscSymbolVariable,
	VscSync,
	VscTable,
	VscTag,
	VscTerminal,
	VscTrash,
	VscTriangleDown,
	VscTriangleUp,
	VscTypeHierarchy,
	VscUnlock,
	VscWarning,
} from "react-icons/vsc";

const iconMap: Record<
	IconName,
	React.ComponentType<{ size?: number | string; className?: string; [key: string]: unknown }>
> = {
	account: VscAccount,
	add: VscAdd,
	"arrow-down": VscArrowDown,
	"arrow-left": VscArrowLeft,
	"arrow-right": VscArrowRight,
	"arrow-up": VscArrowUp,
	beaker: VscBeaker,
	bell: VscBell,
	book: VscBook,
	bookmark: VscBookmark,
	bug: VscBug,
	calendar: VscCalendar,
	check: VscCheck,
	close: VscClose,
	cloud: VscCloud,
	copy: VscCopy,
	database: VscDatabase,
	diff: VscDiff,
	edit: VscEdit,
	error: VscError,
	extensions: VscExtensions,
	eye: VscEye,
	"eye-closed": VscEyeClosed,
	file: VscFile,
	"file-binary": VscFileBinary,
	"file-code": VscFileCode,
	"file-media": VscFileMedia,
	"file-pdf": VscFilePdf,
	"file-submodule": VscFileSubmodule,
	"file-symlink": VscFileSymlinkFile,
	"file-zip": VscFileZip,
	files: VscFiles,
	flame: VscFlame,
	folder: VscFolder,
	"folder-active": VscFolderActive,
	"folder-library": VscFolderLibrary,
	"folder-opened": VscFolderOpened,
	gear: VscGear,
	"git-commit": VscGitCommit,
	"git-merge": VscGitMerge,
	"git-pull-request": VscGitPullRequest,
	github: VscGithub,
	globe: VscGlobe,
	graph: VscGraph,
	history: VscHistory,
	home: VscHome,
	info: VscInfo,
	json: VscJson,
	key: VscKey,
	layers: VscLayers,
	layout: VscLayout,
	link: VscLink,
	"link-external": VscLinkExternal,
	"list-flat": VscListFlat,
	"list-tree": VscListTree,
	lock: VscLock,
	mail: VscMail,
	markdown: VscMarkdown,
	mic: VscMic,
	mute: VscMute,
	"new-file": VscNewFile,
	"new-folder": VscNewFolder,
	note: VscNote,
	notebook: VscNotebook,
	package: VscPackage,
	person: VscPerson,
	play: VscPlay,
	plug: VscPlug,
	record: VscRecord,
	refresh: VscRefresh,
	remote: VscRemote,
	reply: VscReply,
	repo: VscRepo,
	"repo-forked": VscRepoForked,
	rocket: VscRocket,
	"root-folder": VscRootFolder,
	"root-folder-opened": VscRootFolderOpened,
	save: VscSave,
	search: VscSearch,
	send: VscSend,
	server: VscServer,
	settings: VscSettings,
	"settings-gear": VscSettingsGear,
	shield: VscShield,
	"star-empty": VscStarEmpty,
	"star-full": VscStarFull,
	"symbol-class": VscSymbolClass,
	"symbol-enum": VscSymbolEnum,
	"symbol-interface": VscSymbolInterface,
	"symbol-method": VscSymbolMethod,
	"symbol-misc": VscSymbolMisc,
	"symbol-namespace": VscSymbolNamespace,
	"symbol-variable": VscSymbolVariable,
	sync: VscSync,
	table: VscTable,
	tag: VscTag,
	terminal: VscTerminal,
	trash: VscTrash,
	"triangle-down": VscTriangleDown,
	"triangle-up": VscTriangleUp,
	"type-hierarchy": VscTypeHierarchy,
	unlock: VscUnlock,
	warning: VscWarning,
};

export type { IconName };

export interface IconProps extends SVGAttributes<SVGSVGElement> {
	name: IconName;
	size?: number | string;
}

export function Icon({ name, size, className, ...rest }: IconProps) {
	const Component = iconMap[name];
	return <Component size={size} className={className} {...rest} />;
}
