export const IPC = {
	CONNECTION_LIST: "connection:list",
	CONNECTION_GET: "connection:get",
	CONNECTION_CREATE: "connection:create",
	CONNECTION_UPDATE: "connection:update",
	CONNECTION_DELETE: "connection:delete",
	FILE_LIST: "file:list",
	FILE_LIST_DRIVES: "file:listDrives",
	FILE_HOME_DIR: "file:homeDir",
	FILE_PATH_EXISTS: "file:pathExists",
	FILE_GET_LAST_PATH: "file:getLastPath",
	FILE_SET_LAST_PATH: "file:setLastPath",
	FILE_GET_ICON: "file:getIcon",
	REMOTE_CONNECT: "remote:connect",
	REMOTE_DISCONNECT: "remote:disconnect",
	REMOTE_LIST: "remote:list",
	REMOTE_HOME_DIR: "remote:homeDir",
	TERMINAL_SPAWN: "terminal:spawn",
	TERMINAL_WRITE: "terminal:write",
	TERMINAL_RESIZE: "terminal:resize",
	TERMINAL_KILL: "terminal:kill",
	APP_GET_CONFIG_PATH: "app:getConfigPath",
	APP_GET_CONFIG_ERROR: "app:getConfigError",
} as const;
